apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-api2pssale
  labels:
    app: pos-api2pssale
    node: aksp01
    type: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api2pssale
  template:
    metadata:
      labels:
        app: api2pssale
    spec:
      nodeSelector:
        agentpool: aksp01
        "kubernetes.io/os": linux
      containers:
        - name: api2pssale
          image: p703acrsi01.azurecr.io/api/api2pssale:5.20002.0.0504
          ports:
            - containerPort: 44340
          env:
            - name: ENV_Info
              value: "Config from Deployment.yaml"
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ENV_VirtualPath
              value: /api2pssale
            - name: ENV_tRQHost
              value: oJdAbZZDiPhKm2zwB7yovMkv3amkysapsp3DhqXhIKfEkW2nwEV9BMp+D+K6mK4WnwKcqbDm3UY=
            - name: ENV_tRQUsr
              value: "8BP7tjqg/QpswrUHiwMomA=="
            - name: ENV_tRQPwd
              value: "8BP7tjqg/QpswrUHiwMomA=="
            - name: ENV_tRQVirtual
              value: "oklV+QiMfR0lAF3vadbETokcKP/zYuJ3mm1LkIgvyn8="
            - name: ENV_tAccess
              value: "3Wi16CeEjmTEV0XkuI8ddu2F4SyiOeK/nht7vUnDR2CY0pQuiqWtzlJzDY2m9ctCMFOVhYy74etdHTY+z8HKUaavmI+gfFyMCefZqkaVgdU="
            - name: ENV_tConnDB
              value: "Data Source = p703sssi01-sd01.public.ca266396d47e.database.windows.net, 3342;Initial Catalog = AdaAcc;Persist Security Info = True;User ID = administrator_pos;Password = P@ssw0rd@SkcKubo4499;MultipleActiveResultSets=true;"
            - name: ENV_redisIpAddress
              value: ""
